# Generated by Django 5.1.4 on 2025-01-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        ('statuses', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(blank=True, related_name='dishes', to='dishes.dishes', verbose_name='Блюда')),
                ('status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='statuses.status', verbose_name='Статус заказа')),
                ('table_number', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='tables.table', verbose_name='Номер стола')),
            ],
        ),
    ]
